/*
Balika Vadhu- Problem
Send Feedback
Anandi and Jagya were getting married again when they have achieved proper age. 
Dadi Sa invited Alok Nath to do the kanyadaan and give blessings. Alok Nath has 2 blessings. 
Each bessing is in the form of a string consisting of lowercase charaters(a-z) only. 
But he can give only one blessing of K length because some priest told him to do so. 
Thus he decides to generate a blessing using the other two blessings. 
While doing this he wants to ensure that happiness brought into their life by his blessing is maximum.
The generated blessing is a common subsequence of length K of the two blessings he has. 
Happiness of the blessing he generates is calculated by the sum of ASCII values of characters in the blessing and he wants the happiness to be maximum. 
If he is not able to generate a common subsequence of length K then the happiness is 0 (zero). 
Alok Nath comes to you and asks you to find the maximum happiness that can be generated by the two blessings he has.
Input Specification
First line consists of number of test cases t. 
Each test case consists of two strings b1 (blessing 1),b2 (blessing 2) and an integer K, 
each of them in separate lines.
Output Specification
Output consists of t lines each containing an integer denoting the maximum happiness value 
that can be generated by the two blessings.
Constraint
1 <= t <= 50

1 <= length(b1) , length(b2) <= 100 

1 <= K <= 100
Sample Input
2
asdf
asdf
3
anandi
jagya
3
Sample Output
317
0
*/

#include <bits/stdc++.h>
using namespace std;


int balikaVadhuHelper(string b1, string b2, int k){
    if(b1.empty() || b2.empty()){
        return (k == 0) ? 0 : -1;
    }
    int ans;
    if(b1[0] == b2[0]){
        int op1 = balikaVadhuHelper(b1.substr(1), b2.substr(1), k-1);
        if(op1 != -1){
            op1 += b1[0];
        }
        int op2 = balikaVadhuHelper(b1.substr(1), b2, k);
        int op3 = balikaVadhuHelper(b1, b2.substr(1), k);
        ans = max(op1, max(op2, op3));
    }else{
        int op1 = balikaVadhuHelper(b1.substr(1), b2, k);
        int op2 = balikaVadhuHelper(b1, b2.substr(1), k);
        ans = max(op1, op2);
    }
    return ans;
}

int balikaVadhu(string b1, string b2, int k_){
    int ans = balikaVadhuHelper(b1, b2, k_);
    if(ans == -1){
        return 0;
    }
    return ans;
}

int main()
{
 	int t;
    cin >> t;
    while(t--){
        string b1, b2;
        int k_;
        cin >> b1 >> b2 >> k_;
        cout << balikaVadhu(b1, b2, k_) << endl;
    }
    return 0;
}
